name: Firefox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup dependencies
      run: |
        npm install --global web-ext

    - name: Create Archive
      run: |
        web-ext build --filename stopaskinggmu.xpi

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest"
        prerelease: false
        name: "Firefox Extension File"
        files: |
          web-ext-artifacts/stopaskinggmu.xpi


